apiVersion: v1
kind: Service
metadata:
  name: backend-cud-service
  namespace: ingress-nginx

spec:
  selector:
    app: backend-cud
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  type: ClusterIP
